# Generated by Django 4.2.7 on 2025-07-09 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500, unique=True, verbose_name='URL страницы')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок страницы')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='Количество посещений')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальных посетителей')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Популярная страница',
                'verbose_name_plural': 'Популярные страницы',
                'ordering': ['-visit_count'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало сессии')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская сессия',
                'verbose_name_plural': 'Пользовательские сессии',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500, verbose_name='URL страницы')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок страницы')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, null=True, verbose_name='Источник перехода')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Время посещения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение страницы',
                'verbose_name_plural': 'Посещения страниц',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='analytics_p_visited_10fd53_idx'), models.Index(fields=['ip_address'], name='analytics_p_ip_addr_384afc_idx'), models.Index(fields=['user'], name='analytics_p_user_id_91fb05_idx'), models.Index(fields=['page_url'], name='analytics_p_page_ur_eff691_idx')],
            },
        ),
    ]
