# Generated by Django 4.2.7 on 2025-07-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="consultation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка на консультацию",
                "verbose_name_plural": "Заявки на консультации",
            },
        ),
        migrations.AlterField(
            model_name="consultation",
            name="_first_name",
            field=models.CharField(
                db_column="first_name", max_length=255, verbose_name="Имя (зашифровано)"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="_last_name",
            field=models.CharField(
                db_column="last_name",
                max_length=255,
                verbose_name="Фамилия (зашифровано)",
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="is_processed",
            field=models.BooleanField(default=False, verbose_name="Обработано"),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.articlecategory",
                    ),
                ),
            ],
        ),
    ]
