# Generated by Django 4.2.7 on 2025-07-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='pdf_template',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdf/', verbose_name='PDF шаблон'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='word_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/docx/', verbose_name='Word документ'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='word_template',
            field=models.FileField(blank=True, null=True, upload_to='documents/docx/', verbose_name='Word шаблон'),
        ),
    ]
