# Generated by Django 4.2.7 on 2025-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='icon_class',
            field=models.CharField(blank=True, default='fas fa-file-alt', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='faq',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='faq',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя URL для ссылки'),
        ),
    ]
