# Generated by Django 4.2.7 on 2025-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legalnews",
            name="source",
        ),
        migrations.AddField(
            model_name="legalnews",
            name="topic",
            field=models.CharField(
                choices=[
                    ("civil", "Гражданское право"),
                    ("criminal", "Уголовное право"),
                    ("tax", "Налоговое право"),
                    ("labor", "Трудовое право"),
                    ("family", "Семейное право"),
                    ("housing", "Маркетплейсы"),
                    ("none", "Без темы"),
                ],
                default="none",
                max_length=20,
                verbose_name="Тема",
            ),
        ),
    ]
