# Generated by Django 4.2.7 on 2025-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_icon_class_faq_tags_faq_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
