# Generated by Django 4.2.7 on 2025-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_faq_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='faq',
            name='synonyms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Синонимы для поиска'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
