# Generated by Django 4.2.7 on 2025-07-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_documenttemplate_pdf_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='pdf_template',
            field=models.FileField(blank=True, null=True, upload_to='documents\\root\\pdf\\', verbose_name='PDF шаблон'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='word_document',
            field=models.FileField(blank=True, null=True, upload_to='documents\\root\\docx\\', verbose_name='Word документ'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='word_template',
            field=models.FileField(blank=True, null=True, upload_to='documents\\root\\docx\\', verbose_name='Word шаблон'),
        ),
    ]
